import { RoutineConfig, TierChain } from '../types';

function prescription(
  sets: number,
  minReps: number,
  maxReps: number,
  restLabel: string,
  cue: string,
  targetRir = '1-2 RIR',
  finalSetRir?: string,
): NonNullable<TierChain['prescription']> {
  const restSeconds = restLabel.includes('3 min')
    ? 180
    : restLabel.includes('2.5')
      ? 150
      : restLabel.includes('2 min')
        ? 120
        : restLabel.includes('75')
          ? 75
          : restLabel.includes('60')
            ? 60
            : 90;
  const [targetRirMin, targetRirMax] = targetRir.includes('0-1')
    ? [0, 1]
    : targetRir.includes('1-2')
      ? [1, 2]
      : targetRir.includes('2')
        ? [2, 2]
        : [1, 1];

  return {
    sets,
    minReps,
    maxReps,
    targetRir,
    targetRirMin,
    targetRirMax,
    finalSetRir,
    restSeconds,
    restLabel,
    cue,
  };
}

export const gymRoutine: RoutineConfig = {
  id: 'gym',
  name: 'Gym Hypertrophy',
  description: 'Six-day gym routine with delts, chest, back, arms, legs, and recoverable fatigue.',
  icon: 'dumbbell',
  schedule: ['push_a', 'pull_a', 'legs_maintenance', 'push_b', 'pull_b', 'delts_arms'],
  tierChains: [
    {
      slotId: 'push_a_lateral',
      workoutType: 'push_a',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'cable_lateral_raise',
      alternatives: ['db_lateral_raise'],
      exercises: ['cable_lateral_raise'],
      prescription: prescription(5, 12, 20, '90 sec', 'Side delts first. Lead with elbow, no trap heave.', '1-2 RIR', '0-1 RIR only if reps stay clean'),
    },
    {
      slotId: 'push_a_incline_db',
      workoutType: 'push_a',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'db_incline_press',
      alternatives: ['high_incline_machine_press', 'barbell_bench_press'],
      exercises: ['db_incline_press'],
      prescription: prescription(4, 6, 10, '3 min', 'Upper chest after side delts. Deep controlled reps, no grind.'),
    },
    {
      slotId: 'push_a_low_high_fly',
      workoutType: 'push_a',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_fly',
      alternatives: ['pec_deck'],
      exercises: ['cable_fly'],
      prescription: prescription(2, 10, 15, '90 sec', 'Low-to-high arc. Squeeze without shoulder roll.', '1 RIR'),
    },
    {
      slotId: 'push_a_overhead_triceps',
      workoutType: 'push_a',
      fixed: true,
      priority: 'high',
      selectedExercise: 'overhead_tricep_ext',
      alternatives: ['cable_tricep_pushdown'],
      exercises: ['overhead_tricep_ext'],
      prescription: prescription(2, 10, 15, '90 sec', 'Long-head stretch. Elbows fixed.', '0-1 RIR'),
    },
    {
      slotId: 'push_a_pressdown',
      workoutType: 'push_a',
      fixed: true,
      priority: 'support',
      selectedExercise: 'cable_tricep_pushdown',
      alternatives: ['overhead_tricep_ext'],
      exercises: ['cable_tricep_pushdown'],
      prescription: prescription(3, 10, 15, '90 sec', 'Hard lockout, shoulders still.', '0-1 RIR'),
    },

    {
      slotId: 'pull_a_pulldown',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'lat_pulldown',
      alternatives: ['neutral_grip_pulldown', 'pullup'],
      exercises: ['lat_pulldown'],
      prescription: prescription(4, 8, 12, '2.5 min', 'Elbows to ribs. Full stretch.'),
    },
    {
      slotId: 'pull_a_chest_supported_row',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'chest_supported_row',
      alternatives: ['cable_row', 'braced_cable_row'],
      exercises: ['chest_supported_row'],
      prescription: prescription(3, 8, 12, '2.5 min', 'Torso fixed. Pull through elbows.'),
    },
    {
      slotId: 'pull_a_straight_arm',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'high',
      selectedExercise: 'straight_arm_pulldown_cable',
      exercises: ['straight_arm_pulldown_cable'],
      prescription: prescription(2, 12, 15, '90 sec', 'Arms long. Drive hands to hips.', '1 RIR'),
    },
    {
      slotId: 'pull_a_rear_delt',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'cable_rear_delt_fly',
      alternatives: ['reverse_pec_deck', 'cable_face_pull'],
      exercises: ['cable_rear_delt_fly'],
      prescription: prescription(3, 15, 25, '90 sec', 'Wide sweep. Rear delts only.', '0-1 RIR'),
    },
    {
      slotId: 'pull_a_cable_curl',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_curl',
      alternatives: ['db_curl'],
      exercises: ['cable_curl'],
      prescription: prescription(2, 8, 15, '90 sec', 'Elbows pinned. Full stretch.', '0-1 RIR'),
    },
    {
      slotId: 'pull_a_hammer_curl',
      workoutType: 'pull_a',
      fixed: true,
      priority: 'high',
      selectedExercise: 'hammer_curl',
      alternatives: ['db_curl', 'cable_curl'],
      exercises: ['hammer_curl'],
      prescription: prescription(2, 10, 15, '90 sec', 'Neutral grip. Control the eccentric.', '0-1 RIR'),
    },

    {
      slotId: 'legs_hack_or_squat',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'support',
      selectedExercise: 'hack_squat',
      alternatives: ['barbell_squat', 'leg_press'],
      exercises: ['hack_squat'],
      prescription: prescription(2, 6, 10, '3 min', 'Controlled quad work. Leave lower-body fatigue contained.', '2 RIR'),
    },
    {
      slotId: 'legs_rdl',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'support',
      selectedExercise: 'romanian_deadlift',
      alternatives: ['glute_machine', 'leg_curl_machine'],
      exercises: ['romanian_deadlift'],
      prescription: prescription(2, 6, 10, '3 min', 'Hamstring stretch. Low back quiet.', '2 RIR'),
    },
    {
      slotId: 'legs_leg_press',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'support',
      selectedExercise: 'leg_press',
      alternatives: ['hack_squat'],
      exercises: ['leg_press'],
      prescription: prescription(2, 10, 15, '2 min', 'Productive quad volume without grinders.'),
    },
    {
      slotId: 'legs_curl',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'support',
      selectedExercise: 'leg_curl_machine',
      exercises: ['leg_curl_machine'],
      prescription: prescription(2, 8, 12, '90 sec', 'Curl hard. Slow return.', '1 RIR'),
    },
    {
      slotId: 'legs_extension',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'support',
      selectedExercise: 'leg_extension_machine',
      exercises: ['leg_extension_machine'],
      prescription: prescription(2, 10, 15, '90 sec', 'Smooth knee extension. No joint pain reps.', '1 RIR'),
    },
    {
      slotId: 'legs_calf',
      workoutType: 'legs_maintenance',
      fixed: true,
      priority: 'aesthetic',
      selectedExercise: 'standing_calf_raise_machine',
      alternatives: ['calf_raise'],
      exercises: ['standing_calf_raise_machine'],
      prescription: prescription(3, 8, 15, '90 sec', 'Full stretch, full peak.', '1 RIR'),
    },

    {
      slotId: 'push_b_lateral',
      workoutType: 'push_b',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'cable_lateral_raise',
      alternatives: ['db_lateral_raise'],
      exercises: ['cable_lateral_raise'],
      prescription: prescription(4, 12, 20, '90 sec', 'Side delts first. Quality over load.', '1-2 RIR', '0-1 RIR only if reps stay clean'),
    },
    {
      slotId: 'push_b_incline_db',
      workoutType: 'push_b',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'db_incline_press',
      alternatives: ['high_incline_machine_press'],
      exercises: ['db_incline_press'],
      prescription: prescription(3, 8, 12, '2.5 min', 'Upper chest. Match sides.'),
    },
    {
      slotId: 'push_b_bench',
      workoutType: 'push_b',
      fixed: true,
      priority: 'high',
      selectedExercise: 'barbell_bench_press',
      alternatives: ['db_incline_press'],
      exercises: ['barbell_bench_press'],
      prescription: prescription(2, 6, 10, '3 min', 'Stable press top-up. Do not chase failure.'),
    },
    {
      slotId: 'push_b_fly',
      workoutType: 'push_b',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_fly',
      alternatives: ['pec_deck'],
      exercises: ['cable_fly'],
      prescription: prescription(2, 10, 15, '90 sec', 'Pec-deck/cable fly stimulus without extra pressing.', '1 RIR'),
    },
    {
      slotId: 'push_b_pressdown',
      workoutType: 'push_b',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_tricep_pushdown',
      alternatives: ['overhead_tricep_ext'],
      exercises: ['cable_tricep_pushdown'],
      prescription: prescription(2, 8, 15, '90 sec', 'Hard triceps, quiet shoulders.', '0-1 RIR'),
    },
    {
      slotId: 'push_b_overhead_triceps',
      workoutType: 'push_b',
      fixed: true,
      priority: 'support',
      selectedExercise: 'overhead_tricep_ext',
      alternatives: ['cable_tricep_pushdown'],
      exercises: ['overhead_tricep_ext'],
      prescription: prescription(2, 10, 15, '90 sec', 'Long-head top-up only if elbows feel clean.', '0-1 RIR'),
    },

    {
      slotId: 'pull_b_pulldown',
      workoutType: 'pull_b',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'lat_pulldown',
      alternatives: ['neutral_grip_pulldown', 'pullup'],
      exercises: ['lat_pulldown'],
      prescription: prescription(4, 6, 10, '2.5 min', 'Pulldown or pull-up progression. Elbows down.'),
    },
    {
      slotId: 'pull_b_cable_row',
      workoutType: 'pull_b',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'chest_supported_row',
      alternatives: ['cable_row', 'braced_cable_row'],
      exercises: ['chest_supported_row'],
      prescription: prescription(2, 8, 12, '2.5 min', 'Torso fixed. Pull through elbows.'),
    },
    {
      slotId: 'pull_b_one_arm_lat_row',
      workoutType: 'pull_b',
      fixed: true,
      priority: 'high',
      selectedExercise: 'one_arm_cable_lat_row',
      alternatives: ['straight_arm_pulldown_cable', 'cable_row'],
      exercises: ['one_arm_cable_lat_row'],
      prescription: prescription(3, 10, 15, '90 sec', 'Drive elbow to hip. Bias lat, not twist.', '1 RIR'),
    },
    {
      slotId: 'pull_b_face_pull',
      workoutType: 'pull_b',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'cable_face_pull',
      alternatives: ['cable_rear_delt_fly', 'reverse_pec_deck'],
      exercises: ['cable_face_pull'],
      prescription: prescription(4, 15, 25, '90 sec', 'Posture and rear delt work. Smooth external rotation.', '1 RIR'),
    },
    {
      slotId: 'pull_b_hammer_curl',
      workoutType: 'pull_b',
      fixed: true,
      priority: 'high',
      selectedExercise: 'hammer_curl',
      alternatives: ['cable_curl', 'db_curl'],
      exercises: ['hammer_curl'],
      prescription: prescription(2, 10, 15, '90 sec', 'Brachialis and forearm sleeve thickness without another lat-fatigue slot.', '0-1 RIR'),
    },

    {
      slotId: 'delts_arms_lateral_cable',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'critical',
      selectedExercise: 'cable_lateral_raise',
      alternatives: ['db_lateral_raise'],
      exercises: ['cable_lateral_raise'],
      prescription: prescription(5, 15, 25, '90 sec', 'Pure side-delt volume. Stop when traps take over.', '0-1 RIR'),
    },
    {
      slotId: 'delts_arms_rear_delt',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_rear_delt_fly',
      alternatives: ['reverse_pec_deck', 'cable_face_pull'],
      exercises: ['cable_rear_delt_fly'],
      prescription: prescription(4, 15, 25, '75 sec', 'Posture top-up. Rear delts only, traps quiet.', '0-1 RIR'),
    },
    {
      slotId: 'delts_arms_shrug',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'aesthetic',
      selectedExercise: 'db_shrug',
      exercises: ['db_shrug'],
      prescription: prescription(2, 10, 15, '2 min', 'Neck-to-shoulder thickness. No rolling.'),
    },
    {
      slotId: 'delts_arms_cable_curl',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'high',
      selectedExercise: 'cable_curl',
      alternatives: ['db_curl'],
      exercises: ['cable_curl'],
      prescription: prescription(2, 10, 15, '90 sec', 'Cable tension. Elbows pinned.', '0-1 RIR'),
    },
    {
      slotId: 'delts_arms_hammer_curl',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'high',
      selectedExercise: 'hammer_curl',
      alternatives: ['db_reverse_curl', 'db_curl', 'cable_curl'],
      exercises: ['hammer_curl'],
      prescription: prescription(2, 10, 15, '90 sec', 'Hammer or reverse curl for brachialis and forearm thickness.', '0-1 RIR'),
    },
    {
      slotId: 'delts_arms_reverse_curl',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'aesthetic',
      selectedExercise: 'db_reverse_curl',
      alternatives: ['hammer_curl'],
      exercises: ['db_reverse_curl'],
      prescription: prescription(2, 12, 18, '75 sec', 'Low-dose forearm top-up. Stop before wrist or elbow irritation.', '1-2 RIR'),
    },
    {
      slotId: 'delts_arms_overhead_triceps',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'high',
      selectedExercise: 'overhead_tricep_ext',
      alternatives: ['cable_tricep_pushdown'],
      exercises: ['overhead_tricep_ext'],
      prescription: prescription(2, 10, 15, '90 sec', 'Long-head stretch. Stop for elbow irritation.', '0-1 RIR'),
    },
    {
      slotId: 'delts_arms_neck_iso',
      workoutType: 'delts_arms',
      fixed: true,
      priority: 'aesthetic',
      selectedExercise: 'neck_iso_ext',
      alternatives: ['neck_iso_flex'],
      exercises: ['neck_iso_ext'],
      prescription: prescription(2, 20, 30, '60 sec', 'Easy neck isometrics. Gentle pressure only.', '2 RIR'),
    },
  ],
};
