import { RoutineConfig } from '../types';

export const gymRoutine: RoutineConfig = {
  id: 'gym',
  name: 'Gym',
  description: 'Free weights and machines. Bench press, barbell squat, deadlift, lat pulldown, cable work.',
  icon: 'dumbbell',
  schedule: ['push', 'pull', 'legs', 'push', 'pull', 'legs'],
  tierChains: [
    // ── PUSH ──────────────────────────────────────────────────────────────────
    {
      slotId: 'gym_push_chest',
      workoutType: 'push',
      fixed: true,
      priority: 'critical',
      exercises: ['barbell_bench_press'],
    },
    {
      slotId: 'gym_push_incline',
      workoutType: 'push',
      fixed: true,
      priority: 'high',
      exercises: ['db_incline_press'],
    },
    {
      slotId: 'gym_push_fly',
      workoutType: 'push',
      fixed: true,
      priority: 'high',
      exercises: ['cable_fly'],
    },
    {
      slotId: 'gym_push_overhead',
      workoutType: 'push',
      fixed: false,
      priority: 'high',
      exercises: ['db_shoulder_press', 'barbell_ohp'],
    },
    {
      slotId: 'gym_push_lateral',
      workoutType: 'push',
      fixed: true,
      priority: 'critical',
      exercises: ['db_lateral_raise'],
    },
    {
      slotId: 'gym_push_lateral_cable',
      workoutType: 'push',
      fixed: true,
      priority: 'critical',
      exercises: ['cable_lateral_raise'],
    },
    {
      slotId: 'gym_push_tricep',
      workoutType: 'push',
      fixed: false,
      priority: 'high',
      exercises: ['cable_tricep_pushdown', 'overhead_tricep_ext'],
    },

    // ── PULL ──────────────────────────────────────────────────────────────────
    {
      slotId: 'gym_pull_vertical',
      workoutType: 'pull',
      fixed: false,
      priority: 'critical',
      exercises: ['lat_pulldown', 'pullup'],
    },
    {
      slotId: 'gym_pull_horizontal',
      workoutType: 'pull',
      fixed: false,
      priority: 'critical',
      exercises: ['cable_row', 'barbell_row'],
    },
    {
      slotId: 'gym_pull_rear_delt',
      workoutType: 'pull',
      fixed: true,
      priority: 'critical',
      exercises: ['cable_face_pull'],
    },
    {
      slotId: 'gym_pull_lat',
      workoutType: 'pull',
      fixed: true,
      priority: 'high',
      exercises: ['straight_arm_pulldown_cable'],
    },
    {
      slotId: 'gym_pull_bicep',
      workoutType: 'pull',
      fixed: false,
      priority: 'high',
      exercises: ['cable_curl', 'barbell_curl'],
    },
    {
      slotId: 'gym_pull_hammer',
      workoutType: 'pull',
      fixed: true,
      priority: 'high',
      exercises: ['hammer_curl'],
    },

    // ── LEGS ──────────────────────────────────────────────────────────────────
    {
      slotId: 'gym_legs_squat',
      workoutType: 'legs',
      fixed: false,
      priority: 'critical',
      exercises: ['barbell_squat', 'front_squat'],
    },
    {
      slotId: 'gym_legs_press',
      workoutType: 'legs',
      fixed: true,
      priority: 'high',
      exercises: ['leg_press'],
    },
    {
      slotId: 'gym_legs_hinge',
      workoutType: 'legs',
      fixed: false,
      priority: 'critical',
      exercises: ['romanian_deadlift', 'barbell_deadlift', 'sumo_deadlift'],
    },
    {
      slotId: 'gym_legs_glute',
      workoutType: 'legs',
      fixed: true,
      priority: 'critical',
      exercises: ['hip_thrust'],
    },
    {
      slotId: 'gym_legs_unilateral',
      workoutType: 'legs',
      fixed: false,
      priority: 'high',
      exercises: ['bulgarian_split_squat'],
    },
    {
      slotId: 'gym_legs_hamstring',
      workoutType: 'legs',
      fixed: true,
      priority: 'high',
      exercises: ['leg_curl_machine'],
    },
    {
      slotId: 'gym_legs_quad',
      workoutType: 'legs',
      fixed: true,
      priority: 'high',
      exercises: ['leg_extension_machine'],
    },
    {
      slotId: 'gym_legs_calf',
      workoutType: 'legs',
      fixed: true,
      priority: 'aesthetic',
      exercises: ['standing_calf_raise_machine'],
    },
    {
      slotId: 'gym_legs_glute_kickback',
      workoutType: 'legs',
      fixed: true,
      priority: 'high',
      exercises: ['cable_glute_kickback'],
    },
    {
      slotId: 'gym_legs_glute_abduction',
      workoutType: 'legs',
      fixed: true,
      priority: 'high',
      exercises: ['hip_abduction_machine'],
    },
  ],
};
