import { Exercise, MobilityExercise } from './types';

// PUSH DAY EXERCISES
export const PUSH_EXERCISES: Exercise[] = [
  {
    key: 'incline_pushup',
    name: 'INCLINE PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'chest',
    instruction: 'Hands in TRX handles at mid-height or against a wall. Body straight. Lower chest toward hands, press back up. Easier angle — build pushing mechanics here before going horizontal.',
    youtubeId: '4dF580BTZRY',
    workoutType: 'push',
  },
  {
    key: 'trx_pushup',
    name: 'TRX PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'chest',
    instruction: 'Hands in TRX handles, body straight. Lower chest between handles, press back up. Harder than regular pushups.',
    youtubeId: 'OlUqeytSoxE',
    workoutType: 'push',
  },
  {
    key: 'pike_pushup',
    name: 'PIKE PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'shoulders',
    instruction: 'Pike position, hips high. Bend elbows, lower head toward floor. Press back up. Targets shoulders.',
    youtubeId: 'XckEEwa1BPI',
    workoutType: 'push',
  },
  {
    key: 'decline_pike_pushup',
    name: 'DECLINE PIKE PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'shoulders',
    instruction: 'Feet elevated on chair. Hips high in pike. Lower crown toward floor, press back up. Heavier overhead load than standard pike push-up.',
    youtubeId: 'XckEEwa1BPI',
    workoutType: 'push',
  },
  {
    key: 'trx_y_raise',
    name: 'TRX Y RAISE',
    unit: 'reps',
    primaryMuscle: 'upper_back',
    instruction: 'Face anchor, lean back. Raise arms into a Y overhead, thumbs up. Squeeze shoulder blades at top. Slow and controlled. Builds upper back width and rear delts.',
    youtubeId: 'SdSZwVpun28',
    workoutType: 'push',
  },
  {
    key: 'trx_upright_row',
    name: 'TRX UPRIGHT ROW',
    unit: 'reps',
    primaryMuscle: 'side_delt',
    instruction: 'Face anchor, lean back 30°, overhand grip. Pull handles up to chin, elbows high and flared wide. Pause at top. Directly loads side delts and upper traps — the two muscles that widen the shoulder silhouette from the front.',
    workoutType: 'push',
  },
  {
    key: 'trx_shrug',
    name: 'TRX SHRUG',
    unit: 'reps',
    primaryMuscle: 'side_delt',
    instruction: 'Face anchor, lean back 45°, arms straight. Keeping arms extended, elevate shoulders as high as possible. Hold 1 sec at top, lower slowly. Upper trap isolation — key for neck-to-shoulder thickness perceived as physical dominance.',
    workoutType: 'push',
  },
  {
    key: 'pushup',
    name: 'PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'chest',
    instruction: 'Hands shoulder-width, body straight. Lower chest to floor, elbows at 45°. Press back up. The core horizontal push — master form here before elevating feet.',
    youtubeId: 'IODxDxX7oi4',
    workoutType: 'push',
  },
  {
    key: 'pushup_feet_elevated',
    name: 'FEET-ELEVATED PUSH-UP',
    unit: 'reps',
    primaryMuscle: 'chest',
    instruction: 'Feet on bench, hands shoulder-width. Lower chest to floor, press back up. Shifts more load to upper chest and shoulders. Keep core tight throughout.',
    workoutType: 'push',
  },
  {
    key: 'bench_dip',
    name: 'BENCH DIP',
    unit: 'reps',
    primaryMuscle: 'triceps',
    instruction: 'Hands on bench behind you, fingers forward. Feet extended forward on ground. Lower until elbows reach 90°, press back up. Back close to bench throughout. Entry-level compound for triceps + lower chest.',
    youtubeId: 'JnLFSFurrpQ',
    workoutType: 'push',
  },
  {
    key: 'dip',
    name: 'PARALLEL BAR DIP',
    unit: 'reps',
    primaryMuscle: 'triceps',
    instruction: 'Grip parallel bars, arms straight. Lean slightly forward, lower until elbows reach 90°. Press up hard. Best compound for triceps + lower chest at the park — full bodyweight loaded.',
    youtubeId: 'wjUmnZH528M',
    workoutType: 'push',
  },
];

// PULL DAY EXERCISES
export const PULL_EXERCISES: Exercise[] = [
  {
    key: 'negative_pullup',
    name: 'PULL-UP NEGATIVE',
    unit: 'reps',
    primaryMuscle: 'lats',
    instruction: 'Jump or step up with chin over bar. Cross feet, brace core. Lower as slowly as possible — minimum 5 seconds, aim for 8–10. Full extension at bottom. Each session add 1 sec per rep. This is the direct path to your first pull-up.',
    youtubeId: '1SBB8C2KJ9k',
    workoutType: 'pull',
  },
  {
    key: 'trx_curl_assisted',
    name: 'TRX BICEP CURL (ASSISTED)',
    unit: 'reps',
    primaryMuscle: 'biceps',
    instruction: 'Face anchor, nearly upright, slight lean back. Palms up, arms extended. Curl handles toward shoulders — elbows stay fixed at your sides. Upright angle reduces load, build the movement pattern here.',
    workoutType: 'pull',
  },
  {
    key: 'trx_curl',
    name: 'TRX BICEP CURL',
    unit: 'reps',
    primaryMuscle: 'biceps',
    instruction: 'Face anchor, lean back 45°. Palms up, arms extended. Curl handles toward shoulders — only forearms move, elbows fixed. Squeeze biceps hard at top. Full load version.',
    workoutType: 'pull',
  },
  {
    key: 'trx_row_steep',
    name: 'TRX ROW (STEEP)',
    unit: 'reps',
    primaryMuscle: 'mid_back',
    instruction: 'Body nearly upright under TRX — feet only slightly in front of anchor. Pull chest to handles, squeeze shoulder blades. Easiest row angle. Build the pull pattern before going more horizontal.',
    youtubeId: 'fW_jdwZT804',
    workoutType: 'pull',
  },
  {
    key: 'trx_kneeling_lat_pulldown',
    name: 'TRX KNEELING LAT PULLDOWN',
    unit: 'reps',
    primaryMuscle: 'lats',
    instruction: 'Kneel facing the anchor. Reach both arms overhead and grip handles. Pull elbows down and back to ribs — like a lat pulldown. Full stretch overhead at top is key for lat width. Walk knees back to make it harder.',
    youtubeId: 't2xgvi9BU1Q',
    workoutType: 'pull',
  },
  {
    key: 'trx_straight_arm_pulldown',
    name: 'TRX STRAIGHT-ARM PULLDOWN',
    unit: 'reps',
    primaryMuscle: 'lats',
    instruction: 'Face anchor high above. Arms straight, lean forward slightly. Drive arms down to hips keeping elbows locked. Squeeze lats hard at bottom. This isolates the lats with a full stretch.',
    youtubeId: 'MrL7odiwMEY',
    workoutType: 'pull',
  },
  {
    key: 'trx_row',
    name: 'TRX ROW',
    unit: 'reps',
    primaryMuscle: 'mid_back',
    instruction: 'Hang under TRX, body straight. Pull chest to handles, squeeze shoulder blades. Lower with control.',
    youtubeId: 'fW_jdwZT804',
    workoutType: 'pull',
  },
  {
    key: 'face_pull',
    name: 'TRX FACE PULL',
    unit: 'reps',
    primaryMuscle: 'rear_delt',
    instruction: 'Lean back holding TRX. Pull handles to face, elbows high and wide. Squeeze rear delts.',
    youtubeId: 'Jbyoxer58j4',
    workoutType: 'pull',
  },
  {
    key: 'trx_t_raise',
    name: 'TRX T RAISE',
    unit: 'reps',
    primaryMuscle: 'rear_delt',
    instruction: 'Face anchor, lean back at 45°. Arms straight at sides, thumbs up. Raise both arms out to a T shape — shoulder height, no higher. Squeeze rear delts at top. Lower slowly. Primarily trains posterior deltoids and rotator cuff — critical for shoulder width from behind and healthy shoulder posture.',
    youtubeId: 'tO9uZImsiRw',
    workoutType: 'pull',
  },
  {
    key: 'trx_reverse_curl_assisted',
    name: 'TRX REVERSE CURL (ASSISTED)',
    unit: 'reps',
    primaryMuscle: 'biceps',
    instruction: 'Stand nearly upright facing anchor, slight lean back only. Palms down, arms extended. Curl handles toward shoulders. Upright angle reduces load — build the movement pattern here before adding weight via body angle. Brachioradialis + forearm extensors.',
    workoutType: 'pull',
  },
  {
    key: 'trx_reverse_curl',
    name: 'TRX REVERSE CURL',
    unit: 'reps',
    primaryMuscle: 'biceps',
    instruction: 'Face anchor, lean back to 45°, palms facing down, arms extended. Curl handles toward shoulders keeping wrists neutral. Full load version. Brachioradialis and forearm extensors — creates the visible forearm thickness seen in short sleeves.',
    workoutType: 'pull',
  },
];

// LEGS DAY EXERCISES
export const LEGS_EXERCISES: Exercise[] = [
  {
    key: 'trx_assisted_squat',
    name: 'TRX ASSISTED SQUAT',
    unit: 'reps',
    primaryMuscle: 'quads',
    instruction: 'Hold TRX lightly for balance only — legs do all the work, TRX does NOT pull you up. Feet hip-width. Sit back and down to depth. Builds squat mechanics before unassisted work.',
    youtubeId: 'ul-yPBFwhnw',
    workoutType: 'legs',
  },
  {
    key: 'bulgarian_split_squat',
    name: 'BULGARIAN SPLIT SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Rear foot elevated on chair/couch. Lower front knee to 90°. Press back up. Start with your weaker leg — match the rep count on both sides, weaker side sets the cap.',
    youtubeId: 'hiLF_pF3EJM',
    workoutType: 'legs',
  },
  {
    key: 'pistol_squat_progression',
    name: 'PISTOL SQUAT PROGRESSION',
    unit: 'reps',
    primaryMuscle: 'quads',
    instruction: 'One leg, hold TRX for balance. Lower slowly on one leg. Press back up. Switch legs each rep.',
    youtubeId: 'ul-yPBFwhnw',
    workoutType: 'legs',
  },
  {
    key: 'glute_bridge',
    name: 'GLUTE BRIDGE',
    unit: 'reps',
    primaryMuscle: 'glutes',
    instruction: 'Lie on back, feet flat, knees bent. Drive hips up, squeeze glutes 1 second at top. Lower slowly with control. Foundation for TRX Hamstring Curl. Start with your weaker side if doing single-leg — match the rep count on both sides.',
    youtubeId: 'OB3jcUgqUSU',
    workoutType: 'legs',
  },
  {
    key: 'trx_hamstring_curl',
    name: 'TRX HAMSTRING CURL',
    unit: 'reps',
    primaryMuscle: 'hamstrings',
    instruction: 'Heels in TRX cradles, face up. Lift hips, curl heels to glutes. Extend legs. Keep hips up entire set.',
    youtubeId: 'JcJ2i2gUW3o',
    workoutType: 'legs',
  },
  {
    key: 'calf_raise',
    name: 'CALF RAISE',
    unit: 'reps',
    primaryMuscle: 'calves',
    instruction: 'Stand on edge of step, hold TRX for balance. Raise up on toes. Lower heels below step. Full range.',
    youtubeId: 'k8ipHzKeAkQ',
    workoutType: 'legs',
  },
  {
    key: 'hip_thrust',
    name: 'HIP THRUST',
    unit: 'weighted',
    primaryMuscle: 'glutes',
    instruction: 'Upper back on bench, feet flat, knees 90°. Drive hips up explosively, squeeze glutes hard at top for 1 sec. Lower controlled. The bench allows full hip extension range — significantly better glute activation than a floor bridge.',
    youtubeId: 'xDmFkJxPzeM',
    workoutType: 'legs',
  },
  {
    key: 'nordic_curl',
    name: 'NORDIC CURL',
    unit: 'reps',
    primaryMuscle: 'hamstrings',
    instruction: 'Kneel, feet anchored under a bar or bench. Arms crossed on chest. Lower torso toward floor as slowly as possible — minimum 3 seconds. Catch with hands if needed. Pull back up using hamstrings, assist with hands only enough to complete the rep. The most effective hamstring builder in calisthenics.',
    workoutType: 'legs',
  },
  {
    key: 'neck_iso_flex',
    name: 'NECK ISO — FRONT',
    unit: 'seconds',
    primaryMuscle: 'neck',
    instruction: 'Sit tall. Both hands on forehead. Press head forward against hand resistance. Do NOT let head move — pure isometric. Hold 10 seconds per rep. Builds sternocleidomastoid and anterior neck — the visible front neck thickness.',
    workoutType: 'legs',
  },
  {
    key: 'neck_iso_ext',
    name: 'NECK ISO — BACK',
    unit: 'seconds',
    primaryMuscle: 'neck',
    instruction: 'Clasp hands behind head. Press head backward against hand resistance. Hold 10 seconds per rep. Builds posterior neck extensors — directly increases neck circumference perceived as formidability.',
    workoutType: 'legs',
  },
];

// GYM PUSH EXERCISES
export const GYM_PUSH_EXERCISES: Exercise[] = [
  {
    key: 'smith_incline_press',
    name: 'SMITH INCLINE PRESS',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Set bench to 30-45 degrees. Lower to upper chest, pause briefly, press without locking hard. Stable upper-chest loading with low setup cost.',
    workoutType: 'push',
  },
  {
    key: 'barbell_bench_press',
    name: 'BARBELL BENCH PRESS',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Lie on flat bench, bar at chest height. Grip slightly wider than shoulder-width. Lower bar to chest with control, elbows at 45°. Press to lockout. Core tight, feet flat on floor.',
    youtubeId: 'rT7DggyJ4ow',
    workoutType: 'push',
  },
  {
    key: 'db_incline_press',
    name: 'INCLINE DUMBBELL PRESS',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Bench at 30-45°. Dumbbells at chest height, elbows at 60°. Press up and slightly together. Superior upper chest activation compared to flat — builds the shelf that\'s visible in a T-shirt.',
    youtubeId: 'DbFgADa2PL8',
    workoutType: 'push',
  },
  {
    key: 'db_shoulder_press',
    name: 'DUMBBELL SHOULDER PRESS',
    unit: 'weighted',
    primaryMuscle: 'shoulders',
    instruction: 'Seated or standing. Dumbbells at ear height, elbows at 90°. Press overhead to near-lockout, don\'t lock out fully. Greater stabilizer demand than barbell. Start here before progressing to OHP.',
    youtubeId: '6Z15_WdXmVw',
    workoutType: 'push',
  },
  {
    key: 'high_incline_machine_press',
    name: 'HIGH-INCLINE MACHINE PRESS',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Seat so handles start around upper chest. Press up and in, keep shoulders down, control the stretch. Use when free benches or Smith are occupied.',
    workoutType: 'push',
  },
  {
    key: 'machine_shoulder_press',
    name: 'MACHINE SHOULDER PRESS',
    unit: 'weighted',
    primaryMuscle: 'shoulders',
    instruction: 'Set seat so handles start near ear height. Press in a smooth arc, stop just short of lockout, lower under control.',
    workoutType: 'push',
  },
  {
    key: 'barbell_ohp',
    name: 'BARBELL OVERHEAD PRESS',
    unit: 'weighted',
    primaryMuscle: 'shoulders',
    instruction: 'Standing, barbell at collarbone, just outside shoulders. Brace core hard. Press overhead to full lockout, bar slightly behind the ear line at top. Most demanding overhead press — heaviest shoulder builder.',
    youtubeId: '2yjwXTZQDDI',
    workoutType: 'push',
  },
  {
    key: 'db_lateral_raise',
    name: 'DUMBBELL LATERAL RAISE',
    unit: 'weighted',
    primaryMuscle: 'side_delt',
    instruction: 'Slight elbow bend, lift arms to shoulder height at sides. Lead with elbows not hands — pour water from a jug. Pause 1 sec at top. Lower slowly (3 sec). Primary side delt isolation — the exercise that widens shoulders the most.',
    youtubeId: 'kDqklk1ZESo',
    workoutType: 'push',
  },
  {
    key: 'machine_lateral_raise',
    name: 'MACHINE LATERAL RAISE',
    unit: 'weighted',
    primaryMuscle: 'side_delt',
    instruction: 'Pads just above elbows. Raise to shoulder height, pause, lower slowly. Keep traps quiet and let the machine keep tension stable.',
    workoutType: 'push',
  },
  {
    key: 'cable_y_raise',
    name: 'CABLE Y RAISE',
    unit: 'weighted',
    primaryMuscle: 'side_delt',
    instruction: 'Set cables low and use light handles. Raise in the scapular plane to a controlled Y, thumbs slightly up. Stop before shrugging. This is a side-delt-first top-up with rear-delt and upper-back overlap, not a heavy trap movement.',
    workoutType: 'push',
  },
  {
    key: 'cable_tricep_pushdown',
    name: 'CABLE TRICEP PUSHDOWN',
    unit: 'weighted',
    primaryMuscle: 'triceps',
    instruction: 'Face cable machine, bar or rope at upper chest height. Tuck elbows at sides — keep them pinned throughout. Extend forearms down to full lockout. Squeeze triceps hard at bottom. The safest, most consistent tricep isolation.',
    youtubeId: 'kiuVA0gs3EI',
    workoutType: 'push',
  },
  {
    key: 'overhead_tricep_ext',
    name: 'OVERHEAD TRICEP EXTENSION',
    unit: 'weighted',
    primaryMuscle: 'triceps',
    instruction: 'Cable behind head or EZ bar. Arms overhead, elbows by ears. Lower behind head until forearms are parallel, then extend fully. Long-head stretch at bottom is key — this is the largest portion of the tricep, visible from behind.',
    youtubeId: 'YbX7Wd8jQ-Q',
    workoutType: 'push',
  },
  {
    key: 'cable_fly',
    name: 'CABLE FLY',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Set both cables to shoulder height. Split stance, one cable in each hand. Slight elbow bend throughout — never change the angle. Bring hands together in front of chest like hugging a tree. Squeeze hard at the middle. Return slowly with full stretch. The bench press builds mass; this carves the detail.',
    youtubeId: 'Iwe6AmxVf7o',
    workoutType: 'push',
  },
  {
    key: 'pec_deck',
    name: 'PEC DECK',
    unit: 'weighted',
    primaryMuscle: 'chest',
    instruction: 'Set the seat so handles line up around mid to upper chest. Keep shoulder blades set, sweep the arms together, pause briefly, and return to a controlled stretch without shoulder roll.',
    workoutType: 'push',
  },
  {
    key: 'cable_lateral_raise',
    name: 'CABLE LATERAL RAISE',
    unit: 'weighted',
    primaryMuscle: 'side_delt',
    instruction: 'Low cable at your side, D-handle in opposite hand. Raise arm straight out to shoulder height — lead with the elbow, not the hand. Pause 1 sec at top. Lower slowly under control (3 sec). Cable keeps constant tension through the full range, unlike dumbbells that go slack at the bottom. Run this as a second lateral raise slot to double side delt volume — the highest-SMV muscle in the system.',
    youtubeId: 'PPjDFHf2sCc',
    workoutType: 'push',
  },
  {
    key: 'db_shrug',
    name: 'DUMBBELL SHRUG',
    unit: 'weighted',
    primaryMuscle: 'neck',
    instruction: 'Hold dumbbells at your sides. Elevate shoulders straight up, pause briefly, then lower under control. Keep the neck neutral and avoid rolling the shoulders.',
    workoutType: 'push',
  },
];

// GYM PULL EXERCISES
export const GYM_PULL_EXERCISES: Exercise[] = [
  {
    key: 'lat_pulldown',
    name: 'LAT PULLDOWN',
    unit: 'weighted',
    primaryMuscle: 'lats',
    instruction: 'Wide grip, lean back slightly (15°). Drive elbows down and back toward hips as you pull bar to upper chest. Full stretch at top — don\'t shortchange the range. Machine pull-up: master the pattern here before transitioning to bodyweight.',
    youtubeId: 'CAwf7n6Luuc',
    workoutType: 'pull',
  },
  {
    key: 'neutral_grip_pulldown',
    name: 'NEUTRAL-GRIP PULLDOWN',
    unit: 'weighted',
    primaryMuscle: 'lats',
    instruction: 'Use neutral handles. Pull elbows toward ribs, chest tall, full stretch overhead. Smooth lat-biased pull without shoulder irritation.',
    workoutType: 'pull',
  },
  {
    key: 'pullup',
    name: 'PULL-UP',
    unit: 'weighted',
    primaryMuscle: 'lats',
    instruction: 'Dead hang, grip shoulder-width or slightly wider. Pull until chin clears bar, squeeze lats at top. Lower with full control — don\'t drop. No kipping. The gold standard of vertical pulling strength.',
    youtubeId: 'eGo4IYlbE5g',
    workoutType: 'pull',
  },
  {
    key: 'cable_row',
    name: 'SEATED CABLE ROW',
    unit: 'weighted',
    primaryMuscle: 'mid_back',
    instruction: 'Sit tall, slight lean forward at start. Pull handle to lower sternum, drive elbows back past your sides. Fully extend arms between reps — don\'t bounce. Controls the eccentric. Upper back, rhomboids, rear delts, biceps.',
    youtubeId: 'GZbfZ033f74',
    workoutType: 'pull',
  },
  {
    key: 'one_arm_cable_lat_row',
    name: 'ONE-ARM CABLE LAT ROW',
    unit: 'weighted',
    primaryMuscle: 'lats',
    instruction: 'Set a cable around lower chest height. Brace with the free hand, let the working side reach forward, then drive the elbow toward the hip. Keep the torso quiet and bias the lat instead of twisting.',
    workoutType: 'pull',
  },
  {
    key: 'chest_supported_row',
    name: 'CHEST-SUPPORTED ROW',
    unit: 'weighted',
    primaryMuscle: 'mid_back',
    instruction: 'Chest fixed to pad. Pull elbows back, squeeze mid-back, lower to full reach. Removes lower-back fatigue from rowing volume.',
    workoutType: 'pull',
  },
  {
    key: 'machine_row',
    name: 'MACHINE ROW',
    unit: 'weighted',
    primaryMuscle: 'mid_back',
    instruction: 'Set chest pad so handles start at lower ribs. Pull without leaning back, pause, return with control.',
    workoutType: 'pull',
  },
  {
    key: 'braced_cable_row',
    name: 'BRACED CABLE ROW',
    unit: 'weighted',
    primaryMuscle: 'mid_back',
    instruction: 'Brace one hand or chest against a bench if possible. Row toward hip or lower ribs, keeping torso fixed.',
    workoutType: 'pull',
  },
  {
    key: 'barbell_row',
    name: 'BARBELL ROW',
    unit: 'weighted',
    primaryMuscle: 'mid_back',
    instruction: 'Hip hinge to 45°, bar hanging below chest. Pull bar to lower sternum, elbows at 45°. Don\'t jerk — control the lower. Heavier horizontal pulling load than cable. Major back mass builder.',
    youtubeId: '9efgcAjQe7E',
    workoutType: 'pull',
  },
  {
    key: 'cable_face_pull',
    name: 'CABLE FACE PULL',
    unit: 'weighted',
    primaryMuscle: 'rear_delt',
    instruction: 'Rope attachment at face height. Step back, pull handles toward face with elbows high and wide. Externally rotate at the top — think "show off your biceps" at the end. Rear delts + external rotators. Non-negotiable for shoulder health under heavy pressing load.',
    youtubeId: 'rep-qVOkqgk',
    workoutType: 'pull',
  },
  {
    key: 'cable_rear_delt_fly',
    name: 'CABLE REAR-DELT FLY',
    unit: 'weighted',
    primaryMuscle: 'rear_delt',
    instruction: 'Cables set around shoulder height. Cross handles, sweep arms out wide, pause behind shoulders, lower slowly. Keep traps down.',
    workoutType: 'pull',
  },
  {
    key: 'reverse_pec_deck',
    name: 'REVERSE PEC DECK',
    unit: 'weighted',
    primaryMuscle: 'rear_delt',
    instruction: 'Chest on pad, handles at shoulder height. Open arms wide with soft elbows, pause, return slowly.',
    workoutType: 'pull',
  },
  {
    key: 'db_curl',
    name: 'DUMBBELL CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'Dumbbells at sides, palms forward. Curl up, fully supinate (twist palm up) as you go. Squeeze biceps at top. Lower fully — full extension is the key rep most people skip. Don\'t swing.',
    youtubeId: 'ykJmrZ5v0Oo',
    workoutType: 'pull',
  },
  {
    key: 'db_incline_curl',
    name: 'INCLINE DUMBBELL CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'Bench low incline. Let arms hang behind torso, curl without swinging, squeeze, lower fully into the stretch.',
    workoutType: 'pull',
  },
  {
    key: 'preacher_curl',
    name: 'PREACHER CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'Upper arms fixed on pad. Curl smoothly, stop short of shoulder drift, lower to a deep controlled stretch.',
    workoutType: 'pull',
  },
  {
    key: 'barbell_curl',
    name: 'BARBELL CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'EZ bar or straight bar, shoulder-width grip. Elbows fixed at sides. Curl to chest, squeeze at top. Lower with control — 2 sec eccentric. Greater load potential than dumbbells, allowing progressive overload over months.',
    youtubeId: 'kwG2ipFRgfo',
    workoutType: 'pull',
  },
  {
    key: 'straight_arm_pulldown_cable',
    name: 'STRAIGHT-ARM PULLDOWN',
    unit: 'weighted',
    primaryMuscle: 'lats',
    instruction: 'Face high cable, straight bar or rope. Arms straight throughout — elbows locked. Drive hands down to hips in an arc. Squeeze lats hard at bottom. Full lat stretch at top. Isolates lats without involving biceps.',
    youtubeId: 'MrL7odiwMEY',
    workoutType: 'pull',
  },
  {
    key: 'cable_curl',
    name: 'CABLE CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'Low cable, EZ bar or straight bar attachment. Elbows pinned at sides throughout. Curl to chest, squeeze hard at top. Lower fully — the cable keeps tension at the bottom stretch where dumbbells go slack. That constant tension is why cables outperform dumbbells for bicep size.',
    youtubeId: 'av7-8CzC9Fk',
    workoutType: 'pull',
  },
  {
    key: 'hammer_curl',
    name: 'HAMMER CURL',
    unit: 'weighted',
    primaryMuscle: 'biceps',
    instruction: 'Neutral grip — thumbs up the entire rep. Curl up without rotating the forearm at any point. Targets brachialis and brachioradialis, the muscles that push the bicep up and create visible arm thickness from the front and the side. Don\'t supinate at the top.',
    youtubeId: 'TwD-YGVP4Bk',
    workoutType: 'pull',
  },
  {
    key: 'db_reverse_curl',
    name: 'DUMBBELL REVERSE CURL',
    unit: 'weighted',
    primaryMuscle: 'forearms',
    instruction: 'Overhand grip, elbows pinned. Curl without wrist bend, pause near the top, lower slowly. Low-dose brachioradialis and forearm extensor work for visible sleeve-to-wrist thickness.',
    workoutType: 'pull',
  },
];

// GYM LEGS EXERCISES
export const GYM_LEGS_EXERCISES: Exercise[] = [
  {
    key: 'goblet_squat',
    name: 'GOBLET SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Hold dumbbell or kettlebell at chest with both hands. Feet hip-width, toes out 15°. Squat deep — elbows inside knees at bottom. Tall torso. Best beginner squat for learning depth and positioning before loading a barbell.',
    youtubeId: 'MxsFDhcyFyE',
    workoutType: 'legs',
  },
  {
    key: 'barbell_squat',
    name: 'BARBELL SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Bar on upper traps (high bar). Brace core hard, take a big breath before descent. Squat to parallel or below — hips below knees. Drive knees out. Stand up through the heels. King of compound leg exercises.',
    youtubeId: 'ultWZbUMPL8',
    workoutType: 'legs',
  },
  {
    key: 'hack_squat',
    name: 'HACK SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Feet mid-platform, torso pinned. Squat deep without hip tuck, drive through mid-foot, avoid hard lockout.',
    workoutType: 'legs',
  },
  {
    key: 'smith_squat',
    name: 'SMITH SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Feet slightly forward under Smith path. Squat to controlled depth, keep knees tracking toes, stand without bouncing.',
    workoutType: 'legs',
  },
  {
    key: 'romanian_deadlift',
    name: 'ROMANIAN DEADLIFT',
    unit: 'weighted',
    primaryMuscle: 'hamstrings',
    instruction: 'Hold bar at hips, soft knee bend. Hinge at hips, bar stays close to legs, lower until strong hamstring stretch (mid-shin for most). Drive hips forward to return — squeeze glutes at top. Primary hamstring + glute hypertrophy exercise.',
    youtubeId: 'JCXUYuzwNrM',
    workoutType: 'legs',
  },
  {
    key: 'cable_pull_through',
    name: 'CABLE PULL-THROUGH',
    unit: 'weighted',
    primaryMuscle: 'glutes',
    instruction: 'Cable set low, rope between legs. Hips back with a slight knee bend, stretch glutes and hamstrings, then drive hips forward. Use a controlled eccentric. Do not turn it into a squat, and do not hyperextend the lower back.',
    workoutType: 'legs',
  },
  {
    key: 'barbell_deadlift',
    name: 'BARBELL DEADLIFT',
    unit: 'weighted',
    primaryMuscle: 'hamstrings',
    instruction: 'Bar over mid-foot, hip-width stance. Hinge down, grip outside legs. Brace core maximally — fill belly with air. Push floor away as you stand, bar drags up the shins. Lockout: hips and knees extend simultaneously. Most total muscle mass recruited of any single exercise.',
    youtubeId: 'op9kVnSso6Q',
    workoutType: 'legs',
  },
  {
    key: 'leg_curl_machine',
    name: 'LEG CURL',
    unit: 'weighted',
    primaryMuscle: 'hamstrings',
    instruction: 'Seated or prone. Pad just above heels. Curl heels toward glutes, squeeze hamstrings hard at peak. Lower slowly — 3 sec eccentric. Full extension at bottom. Hamstring isolation: the only machine movement that truly isolates the hamstrings through full range.',
    youtubeId: 'ELOCsoDSmrg',
    workoutType: 'legs',
  },
  {
    key: 'leg_extension_machine',
    name: 'LEG EXTENSION',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Seated, pad on shins just above ankles. Extend legs to full lockout — toes pointed slightly in for better quad engagement. Squeeze quads hard at top for 1 sec. Lower slowly. Direct quad isolation: the terminal knee extension most compound movements miss.',
    youtubeId: 'YyvSfVjQeL0',
    workoutType: 'legs',
  },
  {
    key: 'standing_calf_raise_machine',
    name: 'STANDING CALF RAISE',
    unit: 'weighted',
    primaryMuscle: 'calves',
    instruction: 'Shoulder pads on traps, balls of feet on platform edge. Lower heels fully below platform (full stretch), rise to toes, pause 2 sec at top. Don\'t bounce at the bottom. Full range only — partial reps are almost useless for calves. Gastrocnemius primary.',
    youtubeId: 'gwLzBJYoWlI',
    workoutType: 'legs',
  },
  {
    key: 'glute_machine',
    name: 'GLUTE MACHINE',
    unit: 'weighted',
    primaryMuscle: 'glutes',
    instruction: 'Set the pad just above the working leg and brace against the handles. Drive the thigh back through hip extension, squeeze the glute hard at peak, then return slowly without rotating the hips. Treat it as direct glute work, not a deadlift replacement for hamstrings or back.',
    workoutType: 'legs',
  },
  {
    key: 'front_squat',
    name: 'FRONT SQUAT',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Bar in front rack: fingertips on bar, elbows high and parallel to floor. Elbows must stay up throughout — any drop dumps the bar forward. Squat to depth, torso stays upright. More quad-dominant and upper-back demanding than back squat. Attempt only after consistent back squat form.',
    youtubeId: 'uYumuL_G_V0',
    workoutType: 'legs',
  },
  {
    key: 'leg_press',
    name: 'LEG PRESS',
    unit: 'weighted',
    primaryMuscle: 'quads',
    instruction: 'Feet hip-width on platform, toes slightly out. Lower sled until knees reach 90° — don\'t let lower back peel off the pad. Press through heels to near-lockout, don\'t fully lock knees. Allows the heaviest quad loading in the gym. Use it to drive volume and overload on top of squat without taxing your lower back further.',
    youtubeId: 'IZxyjW7MPJQ',
    workoutType: 'legs',
  },
  {
    key: 'sumo_deadlift',
    name: 'SUMO DEADLIFT',
    unit: 'weighted',
    primaryMuscle: 'hamstrings',
    instruction: 'Wide stance, toes out 45°, grip inside legs. Chest up, brace hard. Push knees out as you drive the floor away — think "spread the floor." More hip and adductor dominant than conventional. Shorter ROM allows heavier loads. Use to break conventional deadlift plateaus or as a glute-focused variation.',
    youtubeId: 'b8-Wdqa6BDs',
    workoutType: 'legs',
  },
  {
    key: 'cable_glute_kickback',
    name: 'CABLE GLUTE KICKBACK',
    unit: 'weighted',
    primaryMuscle: 'glutes',
    instruction: 'Ankle cuff on low cable. Hold the machine for balance, slight forward lean. Kick leg straight back — squeeze glute hard at peak. Do NOT let hip rotate or torso twist. Slow return. Isolates glute max through a different angle than hip thrust — high peak contraction at full extension. Run after hip thrust.',
    workoutType: 'legs',
  },
  {
    key: 'hip_abduction_machine',
    name: 'HIP ABDUCTION MACHINE',
    unit: 'weighted',
    primaryMuscle: 'glutes',
    instruction: 'Sit upright, pads on outer thighs. Push legs apart as wide as possible, squeeze glutes at peak. Return slowly — 3 sec. Targets gluteus medius, the muscle that creates the visible outer glute curve and hip width from behind. Don\'t lean forward — upright posture maximises glute med activation over TFL.',
    workoutType: 'legs',
  },
];

// All exercises combined
export const EXERCISES: Exercise[] = [
  ...PUSH_EXERCISES,
  ...PULL_EXERCISES,
  ...LEGS_EXERCISES,
  ...GYM_PUSH_EXERCISES,
  ...GYM_PULL_EXERCISES,
  ...GYM_LEGS_EXERCISES,
];

export const STORAGE_KEY = 'traindaily_sessions';
export const FIRST_SESSION_KEY = 'traindaily_first_session';
export const MOBILITY_DONE_KEY = 'traindaily_mobility_done';
export const USER_PROFILE_KEY = 'liftday_user_profile';
export const ACTIVE_WORKOUT_DRAFT_KEY = 'liftday_active_workout_draft';
export const DAILY_LOGS_KEY = 'liftday_daily_logs';
export const STORAGE_ISSUES_KEY = 'liftday_storage_issues';

export const REST_DURATION = 90;
export const WARMUP_DURATION_SECONDS = 60;
export const STRETCH_DURATION_SECONDS = 30;

export const DEFAULT_TARGETS_REPS = [8, 8, 8] as const;

// Evidence-based mobility routine (2x/week, 10-15 min)
export const MOBILITY_EXERCISES: MobilityExercise[] = [
  {
    name: 'CAT-COW (DYNAMIC)',
    duration: 60,
    sides: false,
    instruction: 'On hands and knees. Arch back (cow), then round spine (cat). 20 slow reps. Breathe with movement.',
    youtubeId: 'iZ1eZBY4fwM',
  },
  {
    name: 'HIP FLEXOR STRETCH',
    duration: 60,
    sides: true,
    instruction: 'Kneel on one knee, push hips forward. Pulse gently 10x, then hold 20s. Active stretch.',
    youtubeId: 'iZ1eZBY4fwM',
  },
  {
    name: 'THORACIC ROTATION',
    duration: 60,
    sides: true,
    instruction: 'On all fours, hand behind head. Rotate open 15x each side. Full range, controlled.',
    youtubeId: 'QWwiOHexU8I',
  },
  {
    name: 'SCAPULAR CARS',
    duration: 60,
    sides: false,
    instruction: 'Standing. Move shoulder blades: up, back, down, forward. 10 circles each direction. Slow, controlled.',
    youtubeId: 'a9rqTzZaI7s',
  },
  {
    name: 'WRIST & ANKLE CIRCLES',
    duration: 60,
    sides: false,
    instruction: '10 circles each wrist (both directions). 10 circles each ankle. Shake out hands/feet after.',
    youtubeId: 'oMSVe7PWJ3o',
  },
  {
    name: 'DEEP SQUAT HOLD',
    duration: 60,
    sides: false,
    instruction: 'Deep squat, heels down if possible. Hold 30s. Stand, shake out. Repeat. Opens hips.',
    youtubeId: 'wPM8icPu6H8',
  },
  {
    name: 'CHEST OPENER (DYNAMIC)',
    duration: 60,
    sides: false,
    instruction: 'Clasp hands behind back. Lift arms up 20x. Then doorway stretch, pulse gently 15x. Active mobilization.',
    youtubeId: '8wiZpixdHPU',
  },
];
